In [2]:
import numpy as np

In [6]:
def zad1(wektor):
    srednia = np.mean(wektor)
    odchylenie = np.std(wektor)
    mediana = np.median(wektor)
    return float(srednia), float(odchylenie), float(mediana)

print(zad1([1,2,3,4,5,6,1]))

(3.142857142857143, 1.8070158058105024, 3.0)


In [22]:
def zad2(m : int, n: int, wartosc: float):
    return [[wartosc for _ in range(n)] for _ in range(m)]

print(zad2(3,4,1))

[[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]]


In [26]:
def zad3(n: int):
    macierz = np.ones((n,n))
    np.fill_diagonal(macierz, 0)
    return macierz
print(zad3(3))

[[0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]]


In [29]:
def zad4(wartosci):
    hist, _ = np.histogram(wartosci, bins = 256, range = (0,256))
    prawd = hist/np.sum(hist)
    prawd = prawd[prawd > 0]
    entropia = -np.sum(prawd * np.log2(prawd))
    return entropia

print(zad4([10,20,30,40,50]))

2.321928094887362


In [35]:
def zad5(macierz):
    wynik = np.where(macierz < 0, 0, macierz)
    return wynik

macierz = np.array([[1,2,3],[4,-5,6],[-1,2,-1]])
print(zad5(macierz))

[[1 2 3]
 [4 0 6]
 [0 2 0]]


In [39]:
def zad6(macierz, n):
    jedenD = macierz.ravel()
    najwieksze = np.partition(jedenD, -n)[-n:]
    return np.sort(najwieksze)[::-1]

macierz = np.array([[1,2,3],[4,-5,6],[-1,2,-1]])
print(zad6(macierz, n=4))

[6 4 3 2]


In [47]:
def zad7(macierz):
    jedenD = macierz.ravel()
    wartosci, licznik = np.unique(jedenD, return_counts=True)
    return wartosci[np.argmax(licznik)]

macierz = np.array([[-1,2,3],[4,-5,6],[-1,2,-1]])
print(zad7(macierz))

-1


In [58]:
def zad8(macierz):
    condlist = [macierz != 0]
    choicelist = [-macierz]
    wynik = np.select(condlist, choicelist, default=macierz)
    return wynik

macierz = np.array([[1,2,3],[4,-5,6],[-1,2,0]])
print(zad8(macierz))

[[-1 -2 -3]
 [-4  5 -6]
 [ 1 -2  0]]


In [60]:
def zad9(macierz):
    return np.fromfunction(lambda i, j: -macierz[i,j], macierz.shape, dtype=int)

macierz = np.array([[1,2,3],[4,-5,6],[-1,2,0]])
print(zad9(macierz))

[[-1 -2 -3]
 [-4  5 -6]
 [ 1 -2  0]]
