# Języki skryptowe w analizie danych - podstawy języka R 
###### dr inż. Marcin Lawnik

### Język R

> R is a free software environment for statistical computing and graphics. It compiles and runs on a wide variety of UNIX platforms, Windows and MacOS.

[https://www.r-project.org/about.html](https://www.r-project.org/about.html)

### Instalacja

+ [https://cran.r-project.org/mirrors.html](https://cran.r-project.org/mirrors.html)
+ poprzez Anacondę [https://www.anaconda.com/docs/getting-started/working-with-conda/packages/using-r-language](https://www.anaconda.com/docs/getting-started/working-with-conda/packages/using-r-language)


### Przejdźmy do języka R...

### Komentarze

+ 
```
# komentarz
```
+ użycie skrótów klawiaturowych, np. `ctr + /`

### Typy danych

**numeryczne**

In [1]:
x = 3

class(x)

[1] "numeric"

In [2]:
x = 3.14

class(x)

[1] "numeric"

**liczby całkowite**

In [3]:
x =  3L

class(x)

[1] "integer"

**liczby zespolone**

In [4]:
x = 1 + 1i

class(x)

[1] "complex"

**boolowskie**

In [5]:
x = TRUE

class(x)

[1] "logical"

In [6]:
x = FALSE

class(x)

[1] "logical"

**znakowe**

In [7]:
x = "ala lubi R"

class(x)

[1] "character"

In [8]:
x = "3.14"

class(x)

[1] "character"

### Operacje arytmetyczne

**dodawanie**

In [9]:
x = 3
y = 2

x + y

[1] 5

In [10]:
x = 1 + 1i
y = 1 - 1i

x + y

[1] 2+0i

**odejmowanie**

In [11]:
x = 3
y = 2

x - y

[1] 1

**mnożenie**

In [12]:
x = 3
y = 2

x * y

[1] 6

In [13]:
x = 1 + 1i
y = 1 - 1i

x * y

[1] 2+0i

**dzielenie**

In [14]:
x = 3
y = 2

x / y

[1] 1.5

In [15]:
x = 1 + 1i
y = 1 - 1i

x / y

[1] 0+1i

**potęgowanie**

In [16]:
x = 3
y = 2

x ^ y

[1] 9

In [17]:
x = 1 + 1i
y = 2

x ^ y

[1] 0+2i

**reszta z dzielenia**

In [18]:
x = 3
y = 2

x %% y

[1] 1

In [19]:
x = 3
y = 1.4

x %% y

[1] 0.2

**dzielenie całkowitoliczbowe**

In [20]:
x = 3
y = 2

x %/% y

[1] 1

In [21]:
x = 3
y = 1.4

x %/% y

[1] 2

**pierwiastkowanie**

In [22]:
x = 9

sqrt(x)

[1] 3

### Dodatkowe operatory i stałe

**silnia**

In [23]:
x = 3

factorial(x)

[1] 6

**zdefiniowana stała wartość liczby pi**

In [24]:
x = pi

x

[1] 3.141593

### Wektory

In [25]:
wektor = c('ala','lubi',"R")

wektor

[1] "ala"  "lubi" "R"

In [26]:
class(wektor)

[1] "character"

In [27]:
wektor = c(1, 2, 3)

wektor

[1] 1 2 3

In [28]:
wektor = c(2, 3, c(4, 5))

wektor

[1] 2 3 4 5

In [29]:
wektor = seq(5)

wektor

[1] 1 2 3 4 5

In [30]:
wektor = seq(0, 5)

wektor

[1] 0 1 2 3 4 5

In [31]:
wektor = seq(0, 5, 2)

wektor

[1] 0 2 4

In [32]:
wektor = seq(0, 5, 0.5)

wektor

[1] 0.0 0.5 1.0 1.5 2.0 2.5 3.0 3.5 4.0 4.5 5.0

In [33]:
wektor = seq(1, 5, length = 3)

wektor

[1] 1 3 5

In [34]:
wektor = 0:5

wektor

[1] 0 1 2 3 4 5

**operacje na wektorach**

In [35]:
x = c(1,2,3)
y = c(3,4,5)

x + y 

[1] 4 6 8

In [36]:
x = c(1,2,3)
y = c(3,4,5)

x / y 

[1] 0.3333333 0.5000000 0.6000000

In [37]:
x = c(1,2,3)
y = c(3,4,5)

x ^ y 

[1]   1  16 243

In [38]:
x = 2^(0:4)

x

[1]  1  2  4  8 16

In [39]:
x = c(1,2,3)
y = c(3,4,5)

y %% x 

[1] 0 0 2

In [40]:
x = c(1,2,3)
y = c(3,4,5)

y %/% x 

[1] 3 2 1

**sprawdzenie czy element jest w wektorze**

In [41]:
x = c(1,3,5)

1 %in% x

[1] TRUE

In [42]:
x = c(1,3,5)

2 %in% x

[1] FALSE

#### Wybrane funkcje wektorowe

**długość wektora**

In [43]:
x = c(1,3,5)

length(x)

[1] 3

**element największy**

In [44]:
x = c(1,3,5)

max(x)

[1] 5

**element najmniejszy**

In [45]:
x = c(1,3,5)

min(x)

[1] 1

**suma elementów**

In [46]:
x = c(1,3,5)

sum(x)

[1] 9

**iloczyn elementów**

In [47]:
x = c(1,3,5)

prod(x)

[1] 15

**posortowanie wektora**

In [48]:
x = c(5,1,3)

sort(x)

[1] 1 3 5

**odwrócenie wektora**

In [49]:
x = c(1,3,5)

rev(x)

[1] 5 3 1

### Indeksowanie 

**Uwaga** 

Indeksowanie zaczynamy od 1, a nie jak w większości języków od 0.

In [50]:
wektor = c('ala','lubi',"R")

wektor[1]

[1] "ala"

In [51]:
wektor[1:2]

[1] "ala"  "lubi"

In [52]:
wektor[-2]

[1] "ala" "R"

In [53]:
wektor[10]

[1] NA

### Listy

In [54]:
lista = list(c(1,2,3), "ala lubi R", sin)

lista

[[1]]
[1] 1 2 3

[[2]]
[1] "ala lubi R"

[[3]]
function (x)  .Primitive("sin")

**nazywanie elementów listy**

In [55]:
lista = list(num=c(1,2,3), tekst="ala lubi R", funkcja=sin)

lista

$num
[1] 1 2 3

$tekst
[1] "ala lubi R"

$funkcja
function (x)  .Primitive("sin")

**dostęp do elementów listy (poprzez symbol $)**

In [56]:
lista = list(num=c(1,2,3), tekst="ala lubi R", funkcja=sin)

lista$num

[1] 1 2 3

### Macierze

In [57]:
macierz = matrix( c('a','b','c','d','e','f'), nrow = 2, ncol = 3, byrow = TRUE)

macierz

[,1] [,2] [,3]
[1,] a    b    c   
[2,] d    e    f

[https://www.tutorialspoint.com/r/r_data_types.htm](https://www.tutorialspoint.com/r/r_data_types.htm)

**wymiary macierzy**

In [58]:
macierz = matrix( c('a','b','c','d','e','f'), nrow = 2, ncol = 3, byrow = TRUE)

dim(macierz)

[1] 2 3

**liczba wierszy macierzy**

In [59]:
macierz = matrix( c('a','b','c','d','e','f'), nrow = 2, ncol = 3, byrow = TRUE)

nrow(macierz)

[1] 2

**liczba kolumn macierzy**

In [60]:
macierz = matrix( c('a','b','c','d','e','f'), nrow = 2, ncol = 3, byrow = TRUE)

ncol(macierz)

[1] 3

**macierz jednostkowa**

In [61]:
diag(6)

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1    0    0    0    0    0   
[2,] 0    1    0    0    0    0   
[3,] 0    0    1    0    0    0   
[4,] 0    0    0    1    0    0   
[5,] 0    0    0    0    1    0   
[6,] 0    0    0    0    0    1

**macierz diagonalna**

In [62]:
diag(5, nrow=3, ncol=4)

[,1] [,2] [,3] [,4]
[1,] 5    0    0    0   
[2,] 0    5    0    0   
[3,] 0    0    5    0

### Ramki danych

In [63]:
rms = data.frame(
   kierunek = c("matematyka", "informatyka"), 
   ilu_studentow_I = c(200, 400), 
   ilu_studentow_II = c(60,30)
)
rms

kierunek    ilu_studentow_I ilu_studentow_II
1 matematyka  200             60              
2 informatyka 400             30

### Zmienne i operator przypisania `=` lub `<-` lub `->`

In [64]:
x1 = c("Ala","lubi","R")           

x2 <- c("Ala","lubi","R")   
   
c("Ala","lubi","R") -> x3  

print(x1)
print(x2)
print(x3)

[1] "Ala"  "lubi" "R"   
[1] "Ala"  "lubi" "R"   
[1] "Ala"  "lubi" "R"   


### Więcej o operatorach [https://www.tutorialspoint.com/r/r_operators.htm](https://www.tutorialspoint.com/r/r_operators.htm)

## Instrukcje sterujące

### Instrukcja warunkowa

```
if ( warunek_1 ) {
    blok instrukcji 1
} else if ( warunek_2 ) {
    blok instrukcji 2
} else if ( warunek_3 ) {
    blok instrukcji 3
} else
    blok instrukcji 4
```

In [65]:
x = 2
if (x %% 2 == 0) {
    print("liczba jest parzysta")
} else {
    print("liczba jest nieparzysta")
}    

[1] "liczba jest parzysta"


### Pętla for

```
for ( obiekt in obiekt_iterowalny ){
    blok instrukcji
}
```

In [66]:
x = c("ala", "lubi", "R")
for ( i in x ){
    print(i)
}

[1] "ala"
[1] "lubi"
[1] "R"


In [67]:
x = c(1:10)
for (i in x){
    if( i %% 2 == 0){
        print(i)
    }
}

[1] 2
[1] 4
[1] 6
[1] 8
[1] 10


### Pętla while

```
while ( warunek ){
    blok instrukcji
}
```

In [68]:
x = 0

while( x < 10){
    print(x)
    x = x + 1
}

[1] 0
[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9


# Funkcje

### Definicja i wywołanie
 
Funkcja w R to zbiór instrukcji, który ma być realizowany każdorazowo po jego wywołaniu.
Aby zdefiniować funkcję konieczne jest:
+ podanie nazwy funkcji,
+ określenie elementów wejściowych,
+ użycie słowa kluczowego `function`,
+ umieszczenie kodu w ciele funkcji,
+ `return(wyrażenie)` w razie potrzeby w ciele

```
nazwaFunkcji = function(){ciało funkcji}
```
+ Wewnątrz `()` mogą znajdować się argumenty, które domyślnie mają swój porządek

```
nazwaFunkcji = function(argument1, argument2){ciało funkcji}
```
Funkcję wywołujemy poprzez użycie jej nazwy z odpowiednim zestawem argumentów.

**Uwaga**

Jeśli nie ma w ciele funkcji `return` to zwracane jest ostatnie wyrażenie.

In [69]:
kwadrat = function(x){ x^2 }

kwadrat(2)

[1] 4

In [70]:
kwadrat_2 = function(x){ return(x^2) }

kwadrat_2(2)

[1] 4

In [71]:
kwadrat_3 = function(x) x^2
kwadrat_3(2)

[1] 4

**Metoda `is.function()` i składowe funkcji**

In [72]:
kwadrat = function(x) x^2

mode(kwadrat)
is.function(kwadrat)
is.vector(kwadrat)

[1] "function"

[1] TRUE

[1] FALSE

In [73]:
kwadrat = function(x) x^2

formals(kwadrat) # lista parametrów
body(kwadrat) # wyrażenie (ciało funkcji)
print(kwadrat) # cały kod funkcji
body(body)

$x



x^2

function(x) x^2


{
    if (is.character(fun)) 
        fun <- get(fun, mode = "function", envir = parent.frame())
    .Internal(body(fun))
}

**Funkcje na obiektach**

In [74]:
kwadrat = function(x) x^2

y = 32
kwadrat(y)

kwadrat(1:5)

[1] 1024

[1]  1  4  9 16 25

### Wskazówki

+ Funkcje pozwalają programować na dużym poziomie abstrakcji. Tworzymy obliczenia dla jakichś danych wejściowych, a następnie wywołujemy je na konkretnych obiektach.
+ Dobrze napisana funkcja pozwala zaoszczędzić nasz czas - wystarczy jej używać, kiedy chcemy przeprowadzić obliczenia danego typu. Nie musimy powtarzać tych samych fragmentów kodu tam, gdzie chcemy przeprowadzać podobne obliczenia.

### Bloki wyrażeń

+ Rzadko kiedy ciała pisanych funkcji będą składały się z jednego nieskomplikowanego wyrażenia.
+ Do grupowania ciągów wyrażeń (dowolnej ich liczby), które będą traktowane przez język R jako pojedyncze wyrażenia służą - bloki. Tworzymy je poprzez nawiasy klamrowe, tj. `{}`.

In [75]:
wypisz_wektor = function(wekt){
    cat('Wektor ', length(wekt), '-elementowy. Wartości: ', sep='') # funkcja cat to wypisanie wartości ze znakami specjalnymi
    cat(wekt, sep=', ') # sep oznacza separator
    cat('\n') # \n oznacza nową linię
}

wypisz_wektor(1:5)

Wektor 5-elementowy. Wartości: 1, 2, 3, 4, 5


### Zasięg nazw w funkcjach

Przyjrzyjmy się w jaki sposób prowadzone są obliczenia wewnątrz funkcji na obiektach nazwanych, a dokładniej - jakie są relacje międy nazwami tworzonymi wewnątrz funkcji i pozostałymi.

**zmienne lokalne**
+ zarówno argumenty, jak i obiekty nazwane, tworzone wewnątrz funkcji mają zasięg lokalny, czyli nie są widoczne po zakończeniu ewaluacji wywołania funkcji

In [76]:
x = 1

f1 = function(x){
    x = 2
    print(x)
}

f1(x)

x

[1] 2


[1] 1

**zmienne globalne**

In [77]:
x = 5

f2 = function(){
    x <<- 7
}

print(x)

print(f2())
print(x)

[1] 5
[1] 7
[1] 7


### Parametry i argumenty

**przekazywanie argumentów przez wartość**

In [78]:
f = function(x){
    x[1]=-x[1]
    x
}
y=1:5
f(y)
print(y)

[1] -1  2  3  4  5

[1] 1 2 3 4 5


**parametry z argumentami domyślnymi**

In [79]:
f1 = function(x=8, y=9){
    cat('x=', x, ' y=', y, '\n', sep='')
}
f1(1,2)        # pełne wywołanie
f1(1)          # pominięty y, tak samo dla f1(x=1)
f1(y=2)        # pominięty x
f1()           # dwa argumenty pominięte

x=1 y=2
x=1 y=9
x=8 y=2
x=8 y=9


### Dziękuję za uwagę