In [45]:
import math
import numpy as np

In [7]:
def zad1(macierz, a):
    wynik = np.isin(macierz, a)
    return wynik

macierz = np.array([[1,2,3],[4,-5,6],[-1,2,0]])
print(zad1(0, macierz))

True


In [10]:
def zad2(a):
    x = np.log(a)
    return np.exp(x.mean())

wektor = [1,2,3,4,5,6,7]
print(zad2(wektor))

3.3800151591412964


In [12]:
def zad3(a,b):
    return np.dot(a,b)

v1 = [1,2,3,4,5]
v2 = [6,7,8,9,10]
print(zad3(v1,v2))

130


In [14]:
def zad4(m : int, n: int, wartosc: float):
    return [[wartosc for _ in range(n)] for _ in range(m)]

print(zad4(3,4,1))

[[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]]


In [16]:
def zad5(n: int):
    macierz = np.ones((n,n))
    np.fill_diagonal(macierz, 0)
    return macierz
print(zad5(3))

[[0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]]


In [19]:
def zad6(macierz):
    wynik = np.where(macierz < 0, 0, macierz)
    return wynik

macierz = np.array([[1,2,3],[4,-5,6],[-1,2,-1]])
print(zad6(macierz))

[[1 2 3]
 [4 0 6]
 [0 2 0]]


In [22]:
def zad7(macierz, n):
    jedenD = macierz.ravel()
    najwieksze = np.partition(jedenD, -n)[-n:]
    return np.sort(najwieksze)[::-1]

macierz = np.array([[1,2,3],[4,-5,6],[-1,2,-1]])
print(zad7(macierz, n=4))

[6 4 3 2]


In [24]:
def zad8(macierz):
    jedenD = macierz.ravel()
    wartosci, licznik = np.unique(jedenD, return_counts=True)
    return wartosci[np.argmax(licznik)]

macierz = np.array([[-1,2,3],[4,-5,6],[-1,2,-1]])
print(zad8(macierz))

-1


In [27]:
def zad9(macierz):
    maska = np.apply_along_axis(lambda wiersz: len(np.unique(wiersz)) == len(wiersz), 1, macierz)
    return macierz[maska]

macierz = np.array([[1,2,3],[4,-5,6],[-1,2,-1]])
print(zad9(macierz))

[[ 1  2  3]
 [ 4 -5  6]]


In [31]:
def zad10(P1, P2):
    P1 = np.array(P1)
    P2 = np.array(P2)
    return np.sqrt(np.sum(P1 - P2) ** 2)
P1 = [1,2,3]
P2 = [4,5,6]
print(zad10(P1, P2))

9.0


In [44]:
def zad11(n):
    A = np.array([[1,1],[1,0]])
    wynik = np.identity(2)
    while n > 0:
        if n % 2 == 1:
            wynik = np.dot(wynik, A)
        A = np.dot(A, A)
        n//=2

    return wynik[0][1]
print(zad11(15))

610.0


In [49]:
def zad12(n):
    pierw_5 = math.sqrt(5)
    phi = (1+pierw_5)/2
    psi = (1-pierw_5)/2
    Fn = (phi ** n - psi ** n) / pierw_5
    return round(Fn)
print(zad12(15))

610


In [54]:
def zad13(n, min, max, slad):
    macierz = np.random.randint(min, max + 1, (n, n))
    diag  = np.random.randint(min, max + 1, n)
    diag[-1] = slad - np.sum(diag[:-1])
    np.fill_diagonal(macierz, diag)
    return macierz

print(zad13(4,0,9,20))

[[4 7 4 7]
 [9 2 4 3]
 [4 8 9 6]
 [2 6 6 5]]
