In [1]:
import numpy as np

In [2]:
A = np.array([[3,3,2,1],[2,3,-2,5],[2,3,8,0],[0,0,2,3]])
print(A)

[[ 3  3  2  1]
 [ 2  3 -2  5]
 [ 2  3  8  0]
 [ 0  0  2  3]]


In [17]:
U, E, V_t = np.linalg.svd(A)
print(U)
print()
print(E)
print()
print(V_t)

[[-0.42041918 -0.24886305  0.55377444  0.67427647]
 [-0.12205123 -0.90295473  0.0032413  -0.41202638]
 [-0.87156319  0.29453906 -0.05718518 -0.38775535]
 [-0.22074605 -0.18970153 -0.83069442  0.47458539]]

[9.77680369 7.04977489 3.06464348 0.5681057 ]

[[-0.33226466 -0.43389445 -0.81936119 -0.17315613]
 [-0.27850825 -0.36481111  0.46598549 -0.75644136]
 [ 0.50688949  0.48928748 -0.3321117  -0.62718628]
 [ 0.74504791 -0.66275654  0.03473597  0.06671424]]
